{"uuid":"709ae688-1700-4217-aab0-511cca1e0fa4","historyId":"d5cf21caff9c7c348ca7d6fae8f615e5","fullName":"examples.AssertionTest.devideByZeroTest","labels":[{"name":"package","value":"examples.AssertionTest"},{"name":"testClass","value":"examples.AssertionTest"},{"name":"testMethod","value":"devideByZeroTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"MyWebProject_QA41"},{"name":"subSuite","value":"examples.AssertionTest"},{"name":"host","value":"ULV"},{"name":"thread","value":"6208@ULV.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"devideByZeroTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpected exception of type class examples.AssertionTest but got java.lang.ArithmeticException: / by zero","trace":"org.testng.TestException: \nExpected exception of type class examples.AssertionTest but got java.lang.ArithmeticException: / by zero\r\n\tat org.testng.internal.invokers.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:67)\r\n\tat org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:853)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:718)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.lang.ArithmeticException: / by zero\r\n\tat examples.AssertionTest.devideByZero(AssertionTest.java:15)\r\n\tat examples.AssertionTest.devideByZeroTest(AssertionTest.java:19)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\t... 21 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1710680991931,"stop":1710680991943}